version: '3.8'

services:
  postgres:
    image: postgres
    container_name: POSTGRES_API_V2
    environment:
      POSTGRES_DB: minhaApiV2
      POSTGRES_USER: minhaApiV2
      POSTGRES_PASSWORD: minhaApiV2
    ports:
      - "3333:5432"
    volumes:
      - ./:/var/lib/postgresql/dataMinhaApi
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    networks:
      - minha_api_v2

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: KEYCLOAK_API_V2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: minhaApiV2
      DB_USER: minhaApiV2
      DB_PASSWORD: minhaApiV2
      DB_SCHEMA: minhaapi_keycloack      
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8090:8080
    depends_on:
      - postgres
    networks:
      - minha_api_v2

networks:
  minha_api_v2:
    driver: bridge